version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - compile
      
jobs:
  compile:
    parallelism: 2
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - persist_to_workspace:
          root: tests
      - run: pwd
      - run: ls -ahl
      - run: cd tests && make && make test
