version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - compile
      
jobs:
  compile:
    parallelism: 2
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: gcc -o test cci_tests/test_beginning.c && ./test && rm test
      - run: gcc -o test cci_tests/test_literal.c && ./test && rm test
      - run: gcc -o test cci_tests/test_word.c && ./test && rm test
      - run: gcc -o test cci_tests/test_decimal.c && ./test && rm test
      - run: gcc -o test cci_tests/test_star.c && ./test && rm test
      - run: gcc -o test cci_tests/test_end.c && ./test && rm test
