version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - compile
      
jobs:
  compile:
    parallelism: 2
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: gcc -c regex.c && gcc -o test_regex driver.c && if ./test_regex |grep "Number.* 00"; then echo exit; else echo exit 1; fi
